MODEL:
  NUM_CLASSES: 81
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'childnet'
    OUT_CHANNELS: (40,96,320,640)
  PRIORS:
    FEATURE_MAPS: [40, 20, 10, 5]
    STRIDES: [8, 16, 32, 64]
    MIN_SIZES: [32, 60, 105, 150]
    MAX_SIZES: [60, 105, 150, 195]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("coco_2017_train", )
  TEST: ("coco_2017_val", )
SOLVER:
  MAX_ITER: 400000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/childnet_ssd320_coco'
