MODEL:
  NUM_CLASSES: 21
  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'shufflenet_v2'
    OUT_CHANNELS: (40,96,320)
  PRIORS:
    FEATURE_MAPS: [20, 10, 5]
    STRIDES: [8, 16, 32]
    MIN_SIZES: [30, 52, 75]
    MAX_SIZES: [52, 75, 98]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6]
INPUT:
  IMAGE_SIZE: 160
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/shufflenet_v2_ssd320_voc0712'
